### PR TITLE
Add Python module to requirements.txt

### PR DESCRIPTION
**Pull request by urs-waldmann**
ffmpeg==3.2.4

### CODE REVIEW

**Comment by urs-waldmann** [comment]
Hi!

I had troubles with the script 'process_all.py' without knowing what the issue was. When I looked into the 'Dockerfile' I saw that I missed the ffmpeg module. Maybe you want to add this to the 'requirements.txt' file for people who do not use Docker?

Cheers,
Urs

**Comment by anibali** [comment]
I don't think that you can install ffmpeg 3.2.4 using pip. However, it should definitely be listed as a requirement in the readme so I've added it there (https://github.com/anibali/h36m-fetch/commit/383c24d1651920f9d213fa15b83dcbe07641aa77).

**Comment by urs-waldmann** [comment]
You can pip install ffmpeg. But yes, I also used conda install --no-update-deps -y -c conda-forge ffmpeg=3.2.4.

**Comment by urs-waldmann** [comment]
I think this is done by your comment in the readme.

**Pull request closed without merging**
